### ISSUE TITLE
DS2490 cannot find devices on AMD64 with -O2

### ISSUE THREAD

**Issue by rfinnie** [bcl/digitemp#7]
We had a few reports in Debian/Ubuntu of DS2490 devices not being found on AMD64:

 * https://bugs.debian.org/585431
 * https://bugs.launchpad.net/bugs/452177

The workaround was to compile the binaries with -O0 instead of -O2 on AMD64 which we've been doing for awhile now without complaint, but I'd like to find the root cause and remove the workaround someday.  I really should get a DS2490 device some day to test.

**Comment by desto-kluger** [comment]
I use Digitemp with Debian.
 
DS2490 has been working for me by doing the following:
owTouchReset() located in usblnk.c does not zero a buffer before using it.
 
In userial/df2490/usblnk.c after line 89, add:
   memset(buffer,0,0x20);
 
Or you can zero the buffer with bzero or whatever else, but it must be zeroed because usb_bulk_read() sometimes only returns 16 bytes, and so when byte 17 is checked (in line 102) it will be unpredictable.
 
It is worth asking, why does usb_bulk_read() sometimes return 16 bytes and sometimes 32.... I didn't look into that.... if you do look into it, please share.  I have observed this usb_bulk_read() problem on every distribution of linux that I have used.  Zeroing the buffer has fixed the problem.
 
I also have working:
   -Hobby Board 4ch hubs
   -nested hubs
 
The following code is sloppy, but maybe it is still of interest to someone.
Here it is:  [ https://github.com/desto-kluger/digitemp-v3.6.0-DRJ ]( https://github.com/desto-kluger/digitemp-v3.6.0-DRJ )
 
desto-kluger
 
-----Original Message-----

**Comment by bcl** [comment]
I've included clearing the buffer, and it appeared to work ok for a while, and then started failing again. Right now it's reporting that the serial port 'USB' doesn't exist, even after unplugging it for a bit and it showing up in lsusb just fine. I still don't trust the DS2490, but thanks for the code, it certainly can't hurt to make sure the buffer is zeroed.

**Comment by rfinnie** [comment]
I received a DS2490-based DS9490R# yesterday and have been playing with it, and it's been pretty stable against HEAD, even with standard -O2 (though I admit I haven't tried older versions with the same hardware).  @desto-kluger thanks for the pointer; I think this can be closed now.
